title: Портфолио
optionalCategoryIndex: true
supportedLanguages: []
syntax: XML
properties: []
logo: person-fairy-duotone-solid-full.svg
description: "Анна Кравченко: резюме и примеры работ"
style: blue-pink
